#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Build every file the release workflow publishes, under dist/:
#
#   DeepTally-X.Y.Z.dmg            the app (via Scripts/dmg.sh)
#   deeptally-X.Y.Z-arm64.tar.gz   the CLI binary + DeepTally_DeepTallyCore.bundle at the archive root
#   install.sh                     a copy of Scripts/install.sh
#   deeptally.rb                   the Homebrew formula, rendered for this version and tarball
#   SHA256SUMS                     shasum -a 256 lines for the artifacts above
#
# Usage: VERSION=X.Y.Z Scripts/release-assets.sh
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="${VERSION:-0.1.0}"
APP_NAME="DeepTally"
CLI_NAME="deeptally"
CORE_BUNDLE="DeepTally_DeepTallyCore.bundle"
DMG="dist/${APP_NAME}-${VERSION}.dmg"
TARBALL="dist/${CLI_NAME}-${VERSION}-arm64.tar.gz"

fail() {
  echo "error: $*" >&2
  exit 1
}

case "$VERSION" in
  ""|*[!0-9A-Za-z.+-]*)
    fail "VERSION='$VERSION' is not a version number — run: VERSION=X.Y.Z make release-assets"
    ;;
esac

echo "==> release assets for v$VERSION"

echo "==> app bundle and DMG"
VERSION="$VERSION" ./Scripts/bundle.sh
VERSION="$VERSION" ./Scripts/dmg.sh

echo "==> CLI tarball"
swift build -c release --arch arm64
BIN_PATH="$(swift build -c release --arch arm64 --show-bin-path)"
[ -x "$BIN_PATH/$CLI_NAME" ] || fail "no $CLI_NAME binary in $BIN_PATH — run 'make build' and try again"
[ -d "$BIN_PATH/$CORE_BUNDLE" ] || fail "no $CORE_BUNDLE in $BIN_PATH — run 'make build' and try again"

STAGE="dist/cli-stage"
rm -rf "$STAGE" "$TARBALL"
mkdir -p "$STAGE"
cp "$BIN_PATH/$CLI_NAME" "$STAGE/$CLI_NAME"
cp -R "$BIN_PATH/$CORE_BUNDLE" "$STAGE/$CORE_BUNDLE"

# The CLI reports its version from the Version.txt resource in this bundle (Sources/DeepTallyCore/
# Version.swift), so the staged copy is what carries the release version. The path is discovered rather
# than assumed: the bundle layout differs between SwiftPM toolchains (flat vs Contents/), and
# Bundle.module is what the CLI itself uses to find the file.
VERSION_FILE="$(find "$STAGE/$CORE_BUNDLE" -type f -name Version.txt -print -quit)"
[ -n "$VERSION_FILE" ] || fail "no Version.txt inside $CORE_BUNDLE — the bundle layout changed; refusing to publish $TARBALL"
printf '%s\n' "$VERSION" > "$VERSION_FILE"

# The CLI must read the price table and holiday calendar out of the bundle that ships beside it,
# or the archive layout is wrong. 'rate' needs no key and exercises both resources.
if ! "$STAGE/$CLI_NAME" rate >/dev/null 2>&1; then
  rm -rf "$STAGE"
  fail "the staged $CLI_NAME could not run 'rate' — it cannot find its bundled resources; refusing to publish $TARBALL"
fi

# v0.1.0 shipped a CLI that reported 0.1.0-dev, because the version was a source constant the pipeline
# never touched. A staged CLI that does not report this release's version is not publishable.
reported="$("$STAGE/$CLI_NAME" --version | awk '{ print $2 }')"
if [ "$reported" != "$VERSION" ]; then
  rm -rf "$STAGE"
  fail "the staged $CLI_NAME reports '$reported', not '$VERSION' — refusing to publish $TARBALL"
fi

# Homebrew installs the binary and its bundle in libexec behind a bin wrapper (the formula cannot use a
# symlink: SwiftPM's resource accessor does not resolve one). Prove that layout here, where it is a gate
# — v0.1.1's formula crashed in it after publishing.
BREW_SIM="$(mktemp -d)"
mkdir -p "$BREW_SIM/libexec" "$BREW_SIM/bin"
cp "$STAGE/$CLI_NAME" "$BREW_SIM/libexec/$CLI_NAME"
cp -R "$STAGE/$CORE_BUNDLE" "$BREW_SIM/libexec/$CORE_BUNDLE"
printf '#!/bin/bash\nexec "%s" "$@"\n' "$BREW_SIM/libexec/$CLI_NAME" > "$BREW_SIM/bin/$CLI_NAME"
chmod +x "$BREW_SIM/bin/$CLI_NAME"
brew_reported="$("$BREW_SIM/bin/$CLI_NAME" --version | awk '{ print $2 }')"
rm -rf "$BREW_SIM"
if [ "$brew_reported" != "$VERSION" ]; then
  rm -rf "$STAGE"
  fail "the CLI cannot find its resources behind a Homebrew-style wrapper (reported '$brew_reported') — refusing to publish $TARBALL"
fi

# COPYFILE_DISABLE keeps ._* AppleDouble entries out of the archive (BSDTar would add them).
COPYFILE_DISABLE=1 tar -czf "$TARBALL" -C "$STAGE" "$CLI_NAME" "$CORE_BUNDLE"
rm -rf "$STAGE"

root_entries="$(tar -tzf "$TARBALL" | awk -F/ 'NF > 0 { print $1 }' | sort -u | tr '\n' ' ')"
case "$root_entries" in
  "$CLI_NAME $CORE_BUNDLE "|"$CORE_BUNDLE $CLI_NAME ") ;;
  *)
    fail "$TARBALL has unexpected root entries ('$root_entries') — expected exactly $CLI_NAME and $CORE_BUNDLE"
    ;;
esac

echo "==> install.sh"
cp Scripts/install.sh dist/install.sh
chmod +x dist/install.sh

echo "==> Homebrew formula"
TARBALL_SHA="$(shasum -a 256 "$TARBALL" | awk '{ print $1 }')"
cat > dist/deeptally.rb <<RUBY
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Scripts/release-assets.sh for v$VERSION — do not edit the copy in dist/.
class Deeptally < Formula
  desc "DeepSeek account balance and rate meter (CLI)"
  homepage "https://github.com/genoma/deeptally"
  version "$VERSION"
  url "https://github.com/genoma/deeptally/releases/download/v$VERSION/${CLI_NAME}-$VERSION-arm64.tar.gz"
  sha256 "$TARBALL_SHA"
  license "GPL-3.0-or-later"

  depends_on arch: :arm64
  depends_on macos: :sequoia

  def install
    libexec.install "$CLI_NAME", "$CORE_BUNDLE"
    # A wrapper, not a symlink: SwiftPM's generated resource accessor looks for the bundle beside the
    # path the process was started with and does not resolve symlinks, so a bin symlink hides the
    # libexec bundle (v0.1.1's formula crashed with a Fatal error because of this).
    (bin/"$CLI_NAME").write_env_script libexec/"$CLI_NAME", {}
  end

  test do
    assert_match "$CLI_NAME", shell_output("#{bin}/$CLI_NAME --version")
  end
end
RUBY

echo "==> SHA256SUMS"
(
  cd dist
  shasum -a 256 \
    "${APP_NAME}-${VERSION}.dmg" \
    "${CLI_NAME}-${VERSION}-arm64.tar.gz" \
    install.sh \
    deeptally.rb > SHA256SUMS
)

echo "==> verifying the finished bundle"
( cd dist && shasum -a 256 -c SHA256SUMS ) || fail "SHA256SUMS does not verify its own artifacts — do not publish this directory"

echo "release assets for v$VERSION are in dist/:"
echo "  $DMG"
echo "  $TARBALL"
echo "  dist/install.sh"
echo "  dist/deeptally.rb"
echo "  dist/SHA256SUMS"
